name: Auto Tag on Merge

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    name: Create version tag from Cargo.toml
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from Cargo.toml
        id: get_version
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: 'Cargo.toml'
          field: 'package.version'

      - name: Create and push tag
        id: create_tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ steps.get_version.outputs.value }}"
          tag_exists_error: false
          message: "Release v${{ steps.get_version.outputs.value }}"

      - name: Show tag status
        run: |
          echo "Tag v${{ steps.get_version.outputs.value }} - Already exists: ${{ steps.create_tag.outputs.tag_exists }}"
