name: CI - Rust Check and Test

on: pull_request

# Cancel outdated builds when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always

jobs:
  check-and-test:
    name: Rust check, clippy, and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      # Run check first (fastest)
      - name: cargo check
        run: cargo check
      # Then clippy (reuses check artifacts)
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features
      # Finally test (reuses build artifacts)
      - name: cargo test
        run: cargo test
